# 1. VALORANT
print("----------------------------------------")
print("|               VALORANT               |")
print("----------------------------------------")
print("| Modo: Competitivo                    |")
print("| Genero: Tactical Shooter             |")
print("----------------------------------------")
print("| Practica tu punteria, uso de         |")
print("| habilidades y posicionamiento.       |")
print("----------------------------------------\n")

# 2. CS2
print("----------------------------------------")
print("|                 CS2                  |")
print("----------------------------------------")
print("| Modo: Competitivo                    |")
print("| Genero: Tactical Shooter             |")
print("----------------------------------------")
print("| Entrena el control de recoil, utility|")
print("| y ejecucion de sitios en mapa.       |")
print("----------------------------------------\n")

# 3. FORTNITE
print("----------------------------------------")
print("|               FORTNITE               |")
print("----------------------------------------")
print("| Modo: Competitivo                    |")
print("| Genero: Battle Royale                |")
print("----------------------------------------")
print("| Mejora la velocidad de construccion, |")
print("| edicion y toma de decisiones.        |")
print("----------------------------------------\n")

# 4. ROCKET LEAGUE
print("----------------------------------------")
print("|            ROCKET LEAGUE             |")
print("----------------------------------------")
print("| Modo: Competitivo                    |")
print("| Genero: Deportes / Coches            |")
print("----------------------------------------")
print("| Practica el control aereo, rotacion  |")
print("| de equipo y precision de tiro.       |")
print("----------------------------------------\n")

# 5. IT TAKES TWO
print("----------------------------------------")
print("|             IT TAKES TWO             |")
print("----------------------------------------")
print("| Modo: Cooperativo                    |")
print("| Genero: Plataformas / Aventura       |")
print("----------------------------------------")
print("| La IA analiza la coordinacion de la  |")
print("| pareja y adapta las mecánicas.       |")
print("----------------------------------------\n")

# 6. HELLDIVERS 2
print("----------------------------------------")
print("|             HELLDIVERS 2             |")
print("----------------------------------------")
print("| Modo: Cooperativo                    |")
print("| Genero: Shooter Co-op                |")
print("----------------------------------------")
print("| Analisis en tiempo real del apoyo    |")
print("| de estratagemas y fuego cruzado.     |")
print("----------------------------------------\n")

# 7. OVERCOOKED 2
print("----------------------------------------")
print("|             OVERCOOKED 2             |")
print("----------------------------------------")
print("| Modo: Cooperativo                    |")
print("| Genero: Gestor / Cocina              |")
print("----------------------------------------")
print("| Ayuda a la comunicacion del equipo y |")
print("| prioridad en la entrega de pedidos.  |")
print("----------------------------------------")